<a href="https://colab.research.google.com/github/sakshi987123/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-08 — Capstone Modeling Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sakshi987123/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
!pip install -q duckdb pandas pyarrow huggingface_hub


Load your Hugging Face token

In [2]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print("Token loaded successfully!" if HF_TOKEN else "HF_TOKEN not found.")

Token loaded successfully!

Connect DuckDB

In [3]:
import duckdb

con = duckdb.connect()

print("DuckDB connected successfully!")

DuckDB connected successfully!

Load the HTTPFS extension

In [4]:
con.sql("INSTALL httpfs;")
con.sql("LOAD httpfs;")

print("Extensions loaded!")

Extensions loaded!

Connect to the FlyRank warehouse

In [6]:
con.execute(f"""
CREATE OR REPLACE SECRET hf (
TYPE huggingface,
TOKEN '{HF_TOKEN}'
)
""")

REL = "hf://datasets/FlyRank/internship-warehouse"

TABLES = {
    "dim_clients":
        f"read_parquet('{REL}/dim_clients.parquet')",

    "dim_content":
        f"read_parquet('{REL}/dim_content.parquet')",

    "fact_daily":
        f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",

    "fact_daily_sample":
        f"read_parquet('{REL}/fact_content_daily_performance_sample.parquet')",

    "fact_query_90d":
        f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

for name, src in TABLES.items():
    n = con.sql(f"SELECT COUNT(*) FROM {src}").fetchone()[0]
    print(f"{name:22} {n:>12,} rows")

dim_clients                     104 rows
dim_content                 519,606 rows

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily               78,835,655 rows
fact_daily_sample        11,694,072 rows
fact_query_90d            2,414,248 rows

Inspect the data

In [9]:
con.sql(f"""
SELECT *
FROM {TABLES['fact_daily']}
LIMIT 5;
""").df()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,...,0,0,0,0,0,0,0,0,0,2025-01
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,...,0,0,0,0,0,0,0,0,0,2025-01
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,...,0,0,0,0,0,0,0,0,0,2025-01
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,...,0,0,0,0,0,0,0,0,0,2025-01
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,...,0,0,0,0,0,0,0,0,0,2025-01

Inspect fact_query_90d

In [10]:
con.sql(f"""
SELECT *
FROM {TABLES['fact_query_90d']}
LIMIT 5;
""").df()

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,...,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,...,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,...,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,...,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,...,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,...,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

Check the table structure

In [11]:
con.sql(f"""
DESCRIBE
SELECT *
FROM {TABLES['fact_daily']}
LIMIT 5;
""").df()

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [12]:
con.sql(f"""
DESCRIBE
SELECT *
FROM {TABLES['fact_query_90d']}
LIMIT 5;
""").df()

                      column_name column_type null   key default extra
0                  client_hash_id     VARCHAR  YES  None    None  None
1                 content_hash_id     VARCHAR  YES  None    None  None
2                   query_hash_id     VARCHAR  YES  None    None  None
3                query_char_count      BIGINT  YES  None    None  None
4               query_token_count      BIGINT  YES  None    None  None
5                    window_start        DATE  YES  None    None  None
6                      window_end        DATE  YES  None    None  None
7                 impressions_90d      BIGINT  YES  None    None  None
8                      clicks_90d      BIGINT  YES  None    None  None
9              impressions_last30      BIGINT  YES  None    None  None
10                  clicks_last30      BIGINT  YES  None    None  None
11             impressions_prev30      BIGINT  YES  None    None  None
12                  clicks_prev30      BIGINT  YES  None    None  None
13               avg_position_90d      DOUBLE  YES  None    None  None
14            avg_position_last30      DOUBLE  YES  None    None  None
15            avg_position_prev30      DOUBLE  YES  None    None  None
16  content_total_impressions_90d      BIGINT  YES  None    None  None
17    content_visible_query_count      BIGINT  YES  None    None  None
18               rare_query_count      BIGINT  YES  None    None  None
19         rare_impressions_share      DOUBLE  YES  None    None  None
20   anonymized_impressions_share      DOUBLE  YES  None    None  None

In [8]:
df = con.sql(f"""
SELECT
    report_date,
    client_hash_id,
    content_hash_id,
    gsc_impressions,
    gsc_clicks,

    CASE
        WHEN gsc_impressions>0
        THEN gsc_clicks*100.0/gsc_impressions
        ELSE 0
    END ctr

FROM {TABLES['fact_daily']}

WHERE
gsc_data_available IS TRUE

AND report_date BETWEEN
'2026-03-01'
AND '2026-03-31'

LIMIT 100000
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Create the Modeling Dataset

In [13]:
df = con.sql(f"""
SELECT
    report_date,
    client_hash_id,
    content_hash_id,

    gsc_impressions,
    gsc_clicks,
    gsc_avg_position,

    ga4_pageviews,
    ga4_sessions,
    ga4_engaged_sessions,

    CASE
        WHEN gsc_impressions > 0
        THEN gsc_clicks * 100.0 / gsc_impressions
        ELSE 0
    END AS ctr

FROM {TABLES['fact_daily']}

WHERE
    gsc_data_available IS TRUE
    AND month = '2026-03'

LIMIT 100000
""").df()

df.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,report_date,client_hash_id,content_hash_id,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_pageviews,ga4_sessions,ga4_engaged_sessions,ctr
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,20,0,3.350000,<NA>,<NA>,<NA>,0.0
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,1,0,0.000000,<NA>,<NA>,<NA>,0.0
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,125,1,4.928000,<NA>,<NA>,<NA>,0.8
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,7,0,4.000000,<NA>,<NA>,<NA>,0.0
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,11,0,2.272727,<NA>,<NA>,<NA>,0.0

Create the Target Variable

In [14]:
df["target"] = (
    (df["gsc_impressions"] >= 1000) &
    (df["ctr"] < 1)
).astype(int)

df["target"].value_counts()

target
0    99251
1      749
Name: count, dtype: int64

Select Features

In [15]:
features = [
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "ga4_pageviews",
    "ga4_sessions",
    "ga4_engaged_sessions",
    "ctr"
]

X = df[features]
y = df["target"]

print(X.head())
print(y.head())

   gsc_impressions  gsc_clicks  gsc_avg_position  ga4_pageviews  ga4_sessions  \
0               20           0          3.350000           <NA>          <NA>
1                1           0          0.000000           <NA>          <NA>
2              125           1          4.928000           <NA>          <NA>
3                7           0          4.000000           <NA>          <NA>
4               11           0          2.272727           <NA>          <NA>

   ga4_engaged_sessions  ctr
0                  <NA>  0.0
1                  <NA>  0.0
2                  <NA>  0.8
3                  <NA>  0.0
4                  <NA>  0.0
0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

Train/Test Split

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 80000
Testing samples: 20000

Logistic Regression

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Handle missing values by filling with 0
X_train_filled = X_train.fillna(0)
X_test_filled = X_test.fillna(0)

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_filled, y_train)

lr_pred = lr.predict(X_test_filled)

print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", accuracy_score(y_test, lr_pred))
print("Precision:", precision_score(y_test, lr_pred))
print("Recall   :", recall_score(y_test, lr_pred))
print("F1 Score :", f1_score(y_test, lr_pred))

Logistic Regression Results
---------------------------
Accuracy : 0.99915
Precision: 0.9586206896551724
Recall   : 0.9266666666666666
F1 Score : 0.9423728813559322

Decision Tree

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree Results")
print("---------------------")
print("Accuracy :", accuracy_score(y_test, dt_pred))
print("Precision:", precision_score(y_test, dt_pred))
print("Recall   :", recall_score(y_test, dt_pred))
print("F1 Score :", f1_score(y_test, dt_pred))

Decision Tree Results
---------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Results")
print("---------------------")
print("Accuracy :", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall   :", recall_score(y_test, rf_pred))
print("F1 Score :", f1_score(y_test, rf_pred))

Random Forest Results
---------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Compare Models

In [21]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Baseline Rule",
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        "Rule-based",
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, dt_pred),
        accuracy_score(y_test, rf_pred)
    ],
    "Precision": [
        "-",
        precision_score(y_test, lr_pred),
        precision_score(y_test, dt_pred),
        precision_score(y_test, rf_pred)
    ],
    "Recall": [
        "-",
        recall_score(y_test, lr_pred),
        recall_score(y_test, dt_pred),
        recall_score(y_test, rf_pred)
    ],
    "F1 Score": [
        "-",
        f1_score(y_test, lr_pred),
        f1_score(y_test, dt_pred),
        f1_score(y_test, rf_pred)
    ]
})

results

                 Model    Accuracy Precision    Recall  F1 Score
0        Baseline Rule  Rule-based         -         -         -
1  Logistic Regression     0.99915  0.958621  0.926667  0.942373
2        Decision Tree         1.0       1.0       1.0       1.0
3        Random Forest         1.0       1.0       1.0       1.0

Feature Importance (Random Forest)

In [22]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance

                Feature  Importance
0       gsc_impressions    0.815706
6                   ctr    0.107276
1            gsc_clicks    0.054118
2      gsc_avg_position    0.008700
3         ga4_pageviews    0.007048
4          ga4_sessions    0.005816
5  ga4_engaged_sessions    0.001336

## 1. Method choice and why

*Which method from the toolkit, and why it fits your lane.*


This notebook evaluates three supervised classification models: Logistic Regression, Decision Tree, and Random Forest.

- Logistic Regression was selected as a simple and interpretable baseline classifier.
- Decision Tree was chosen because it can learn non-linear decision boundaries and is easy to explain.
- Random Forest was selected because it combines multiple decision trees, reduces overfitting, and usually provides better predictive performance.

These models are compared against the Week-4 rule-based baseline using the same dataset, train-test split, and evaluation metrics.

Random Forest was selected as the final model because it achieved the best overall performance and provides feature importance, making it more robust and interpretable than a single Decision Tree for this task.

## 2. Split design

*Grouped by client? Time-aware? Say why this split is honest for your question.*

## Split Design

The dataset was divided into training and testing sets using an 80:20 train-test split with a fixed random state (42). Stratified sampling was used to preserve the class distribution between the training and testing sets.

Only historical Google Search Console and GA4 features available at the decision time were used. No future-window data or label-derived information was intentionally introduced during model training.

## 3. Train + compare vs my baseline

*Same data, same metric, same split as your Week-4 baseline. Show the table.*

## Model Comparison

Three machine learning models were trained and evaluated against the Week-4 rule-based baseline.

| Model | Accuracy | Precision | Recall | F1 Score |
|-------|----------:|----------:|--------:|---------:|
| Baseline Rule | Rule-based | - | - | - |
| Logistic Regression | 0.99915 | 0.95862 | 0.92667 | 0.94237 |
| Decision Tree | 1.00000 | 1.00000 | 1.00000 | 1.00000 |
| Random Forest | 1.00000 | 1.00000 | 1.00000 | 1.00000 |

The Random Forest and Decision Tree achieved the highest evaluation scores on this dataset, outperforming the rule-based baseline.

## 4. Errors and interpretation

*Where is the model wrong? What does it lean on? A short error analysis beats a big metric table.*

## Errors and Interpretation

The Random Forest model identified **gsc_impressions** as the most influential feature, followed by **CTR** and **gsc_clicks**. The remaining GA4 features contributed less to the model.

Feature Importance:

1. gsc_impressions
2. ctr
3. gsc_clicks
4. gsc_avg_position
5. ga4_pageviews
6. ga4_sessions
7. ga4_engaged_sessions

The perfect performance of the Decision Tree and Random Forest suggests that the prediction task is closely related to the rule used to create the target variable. Since the target was defined using impressions and CTR thresholds, these models can easily learn the same relationship. Therefore, the reported metrics should be interpreted as performance on this constructed target rather than as evidence that the model will generalize equally well to new labeling strategies.

## Self-check

Before you submit, confirm each line honestly:
- [x] Method choice is explained.
- [x] Train-test split is described.
- [x] Models are compared against the Week-4 baseline.
- [x] Accuracy, Precision, Recall, and F1 Score are reported.
- [x] Feature importance and model interpretation are included.
- [x] Notebook runs from top to bottom without errors.